### ISSUE TITLE
Score in calculate_peaks

### ISSUE THREAD

**Issue by dreamstorm25** [piperod/beepose#5]
What is the score array for  in calculate_peaks function in inference.py ?
score=[0.2,0.2,0.2,0.2,0.2,0.5,0.5,0.5,0.5].
I thought it was a threshold for detection of parts. If so, how are the values decided for each part and why are there 9 values in the list when the number of parts by default is 5 ?

**Comment by piperod** [comment]
You are right, this is an upcoming feature. It was meant to have lower or higher thresholds according to the difficulty of the sample. I think maybe is safe to start with a single one for all the parts. Was this causing you trouble?

**Comment by dreamstorm25** [comment]
At first, I was getting an out of index error because I have 14 parts in my case, when I changed the list to a size of 14 with every value as 0.1, it ran successfully but it did not detect anything.
Warning: omitting connection due to parts that do not belong to skeleton
Warning: connection not found. There are parts that are  not associated with a connection 
{0: [], 1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [], 9: [], 10: [], 11: [], 12: []}

Now I have trained my model only for 20 epochs and very less images because I wanted to see if all the scripts were running, but I was still expecting a prediction even though it would have been wrong. Should I train some more or can there be a fundamental error ?

**Comment by piperod** [comment]
Are you including the skeleton in the annotations file? It seems is not getting them. Can you post your annotation file? Also, did you run your training with the latest version? Now it supports tensorboard so you should be able to see if the attention maps are getting part detections.

**Comment by dreamstorm25** [comment]
I have included the skeleton - attaching my training annotations file and model_params.json [](url)
[annotations.zip](https://github.com/piperod/beepose/files/4232859/annotations.zip)

**Comment by dreamstorm25** [comment]
Adding to the previous comment, the config of the model_params is printed in the terminal : 
{'stages': 6, 'np1': 28, 'np2': 14, 'numparts': 13, 'skeleton': [[1, 2], [2, 3], [3, 4], [3, 6], [3, 8], [4, 5], [6, 7], [8, 9], [8, 11], [8, 13], [9, 10], [11, 12]], 'mapIdx': [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11], [12, 13], [14, 15], [16, 17], [18, 19], [20, 21], [22, 23]], 'gpu': 0, 'batch_size': 10, 'base_lr': 4e-05, 'momentum': 0.9, 'weight_decay': 0.0005, 'gamma': 0.333, 'stepsize': 68053}

**Comment by piperod** [comment]
what is the size of your images?

**Comment by piperod** [comment]
Here is a demo notebook that may ease the debugging.
[demo.zip](https://github.com/piperod/beepose/files/4233018/demo.zip)

**Comment by dreamstorm25** [comment]
Thanks, I will try that. My training images are of different sizes ranging from 250x300 (approx) to 600x600. Are they supposed to be of same sizes ?

**Comment by piperod** [comment]
That may be it. Yes, they supposed to be the same size. but The code should take care of it. I would suggest to put all the images in a single scale. But before doing that , since they are small enough I suggest to try the code but with resize_factor =1 . My images are 2560x 1440 , so I resize by a factor of 4. Also when you have a change check the tensorboard log and check if during training is actually being able to learn anything.

**Comment by dreamstorm25** [comment]
Thanks, I think using the same size images during training is also helping. I can see the error on tensorboard going down and the prediction is working too. But how do you decide the score of the parts ?

**Comment by piperod** [comment]
It usually depends on the data. For me it works with 0.4. I suspect that the bug may be in another place. Could you try printing the output of peaks_all and post them here?

**Comment by dreamstorm25** [comment]
Here is the output of peaks_all and the output. I am using a score of 0.1 for now.
peaks_all : [[(203, 128, 0.1599580943584442, 0)], [(17, 122, 0.1198345497250557, 1), (21, 127, 0.12000273168087006, 2), (199, 128, 0.2246602326631546, 3)], [(13, 119, 0.11818210780620575, 4), (193, 129, 0.22677263617515564, 5)], [(20, 125, 0.10011550039052963, 6), (185, 140, 0.26539346575737, 7), (181, 152, 0.25234320759773254, 8)], [(41, 131, 0.12102106958627701, 9), (40, 132, 0.12113632261753082, 10), (30, 137, 0.12369046360254288, 11), (203, 144, 0.23916129767894745, 12), (192, 221, 0.4139488935470581, 13)], [(29, 114, 0.17130109667778015, 14), (28, 115, 0.17140303552150726, 15), (0, 122, 0.10173377394676208, 16), (204, 133, 0.16701754927635193, 17), (155, 190, 0.10851919651031494, 18)], [(32, 125, 0.43879589438438416, 19), (199, 219, 0.16916389763355255, 20), (138, 220, 0.21778707206249237, 21)], [(183, 118, 0.7977691888809204, 22), (145, 178, 0.3145278990268707, 23), (243, 189, 0.1312788426876068, 24), (247, 190, 0.13138464093208313, 25), (206, 191, 0.16883207857608795, 26)], [(175, 150, 0.17765137553215027, 27), (202, 199, 0.4610573947429657, 28)], [(41, 125, 0.10691359639167786, 29), (215, 214, 0.394205778837204, 30)], [(0, 114, 0.10706938058137894, 31), (19, 119, 0.13366922736167908, 32), (200, 155, 0.32917091250419617, 33), (191, 157, 0.3365577757358551, 34), (190, 158, 0.33651596307754517, 35), (200, 209, 0.412590891122818, 36)], [(32, 121, 0.18781700730323792, 37), (249, 209, 0.3616645634174347, 38), (238, 212, 0.35385242104530334, 39), (236, 213, 0.35346320271492004, 40), (233, 214, 0.35431551933288574, 41), (231, 215, 0.3545897305011749, 42), (136, 221, 0.19932618737220764, 43), (217, 223, 0.3783453404903412, 44)], [(193, 136, 0.23759475350379944, 45), (238, 200, 0.5484399795532227, 46), (133, 210, 0.33547550439834595, 47), (134, 211, 0.3355925977230072, 48)]]
Warning: omitting connection due to parts that do not belong to skeleton
Warning: connection not found. There are parts that are  not associated with a connection 
{0: [[203, 128, 0.1599580943584442]], 1: [[17, 122, 0.1198345497250557], [21, 127, 0.12000273168087006], [199, 128, 0.2246602326631546]], 2: [[13, 119, 0.11818210780620575], [193, 129, 0.22677263617515564]], 3: [[20, 125, 0.10011550039052963], [185, 140, 0.26539346575737], [181, 152, 0.25234320759773254]], 4: [[41, 131, 0.12102106958627701], [40, 132, 0.12113632261753082], [30, 137, 0.12369046360254288], [203, 144, 0.23916129767894745], [192, 221, 0.4139488935470581]], 5: [[29, 114, 0.17130109667778015], [28, 115, 0.17140303552150726], [0, 122, 0.10173377394676208], [204, 133, 0.16701754927635193], [155, 190, 0.10851919651031494]], 6: [[32, 125, 0.43879589438438416], [199, 219, 0.16916389763355255], [138, 220, 0.21778707206249237]], 7: [[183, 118, 0.7977691888809204], [145, 178, 0.3145278990268707], [243, 189, 0.1312788426876068], [247, 190, 0.13138464093208313], [206, 191, 0.16883207857608795]], 8: [[175, 150, 0.17765137553215027], [202, 199, 0.4610573947429657]], 9: [[41, 125, 0.10691359639167786], [215, 214, 0.394205778837204]], 10: [[0, 114, 0.10706938058137894], [19, 119, 0.13366922736167908], [200, 155, 0.32917091250419617], [191, 157, 0.3365577757358551], [190, 158, 0.33651596307754517], [200, 209, 0.412590891122818]], 11: [[32, 121, 0.18781700730323792], [249, 209, 0.3616645634174347], [238, 212, 0.35385242104530334], [236, 213, 0.35346320271492004], [233, 214, 0.35431551933288574], [231, 215, 0.3545897305011749], [136, 221, 0.19932618737220764], [217, 223, 0.3783453404903412]], 12: [[193, 136, 0.23759475350379944], [238, 200, 0.5484399795532227], [133, 210, 0.33547550439834595], [134, 211, 0.3355925977230072]]}

**Comment by piperod** [comment]
Phew, ok , so its doing something. Now, two things, first, it seems that some of the scores are really low, it would be good idea to visualize these prediction. Second,  at the end it outputs a json file with all that it detects, Can you put that one? I

**Comment by dreamstorm25** [comment]
Sure, I have attached it. Is there any difference between using the complete_model and weights_best for inference ? 
[inference_results.zip](https://github.com/piperod/beepose/files/4258563/inference_results.zip)

**Comment by piperod** [comment]
Ok, it seems that is actually working :) The mapping structure is the one that contains the joints. We have code to visualize these results, you would have to take a look at visualization.py. I guess the warning message is only for some of them, I would add a clearer message so it specifies what connection was trying to map as oppose of just a warning that may give the impression that did not work at all.
